// <auto-generated />
using System;
using HISApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HISApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250109005151_finalize")]
    partial class finalize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HISApp.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15a24dfe-845b-4a6b-8381-e6af77b0aee3"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "7eb60dc9-0624-464d-b714-40d7969c1bf1"
                        },
                        new
                        {
                            Id = new Guid("33fa2f3e-373f-4448-b037-57745771946d"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "3357d377-776f-4414-a3eb-2d8e1fd3b025"
                        },
                        new
                        {
                            Id = new Guid("d36412b1-542d-44b9-9dd4-3bf1538149a7"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "ad806a90-0577-4811-bb3e-c7589835476d"
                        },
                        new
                        {
                            Id = new Guid("27e8f53d-a5cd-419c-baa7-8e5545c1aaf9"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "720a2ab3-d717-48e1-81ed-f4319d99f6ba"
                        },
                        new
                        {
                            Id = new Guid("93816845-789a-4e32-967f-40cea279b8a7"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "fd05d6dc-2699-4f5f-bef7-bd12ef130408"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Abdoun"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Jabal Al-Weibdeh"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Sweifieh"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Name = "Dabouq"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Name = "Al-Husun"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Name = "Ar-Ramtha"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 2,
                            Name = "Al-Barheh"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 2,
                            Name = "Ar-Rabieh"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            Name = "Al-Alamieh"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 3,
                            Name = "Ar-Remal"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 3,
                            Name = "Southern Beach"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 3,
                            Name = "Wadi Rum"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 4,
                            Name = "New Zarqa"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 4,
                            Name = "Al-Ruseifa"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 4,
                            Name = "Al-Dhuleil"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 4,
                            Name = "Hashemiyah"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 5,
                            Name = "Theban"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 5,
                            Name = "Mount Nebo"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 5,
                            Name = "Al-Faisaliah"
                        },
                        new
                        {
                            Id = 20,
                            CityId = 5,
                            Name = "Ma'in"
                        },
                        new
                        {
                            Id = 21,
                            CityId = 6,
                            Name = "Salt City"
                        },
                        new
                        {
                            Id = 22,
                            CityId = 6,
                            Name = "Fuheis"
                        },
                        new
                        {
                            Id = 23,
                            CityId = 6,
                            Name = "Ain Al-Basha"
                        },
                        new
                        {
                            Id = 24,
                            CityId = 6,
                            Name = "Mahes"
                        },
                        new
                        {
                            Id = 25,
                            CityId = 7,
                            Name = "Hosha"
                        },
                        new
                        {
                            Id = 26,
                            CityId = 7,
                            Name = "Al-Khalidiya"
                        },
                        new
                        {
                            Id = 27,
                            CityId = 7,
                            Name = "Rubwa Bani Khaled"
                        },
                        new
                        {
                            Id = 28,
                            CityId = 7,
                            Name = "Um Al-Jimmal"
                        },
                        new
                        {
                            Id = 29,
                            CityId = 8,
                            Name = "Tafila City"
                        },
                        new
                        {
                            Id = 30,
                            CityId = 8,
                            Name = "Busaira"
                        },
                        new
                        {
                            Id = 31,
                            CityId = 8,
                            Name = "Al-Hasa"
                        },
                        new
                        {
                            Id = 32,
                            CityId = 8,
                            Name = "Dana"
                        },
                        new
                        {
                            Id = 33,
                            CityId = 9,
                            Name = "Karak Castle"
                        },
                        new
                        {
                            Id = 34,
                            CityId = 9,
                            Name = "Al-Qasr"
                        },
                        new
                        {
                            Id = 35,
                            CityId = 9,
                            Name = "Mu'tah"
                        },
                        new
                        {
                            Id = 36,
                            CityId = 9,
                            Name = "Al-Mazar"
                        },
                        new
                        {
                            Id = 37,
                            CityId = 10,
                            Name = "Bab Amman"
                        },
                        new
                        {
                            Id = 38,
                            CityId = 10,
                            Name = "Souf Camp"
                        },
                        new
                        {
                            Id = 39,
                            CityId = 10,
                            Name = "Sakib"
                        },
                        new
                        {
                            Id = 40,
                            CityId = 10,
                            Name = "Al-Kitta"
                        },
                        new
                        {
                            Id = 41,
                            CityId = 11,
                            Name = "Alghadeer"
                        },
                        new
                        {
                            Id = 42,
                            CityId = 11,
                            Name = "Petra"
                        },
                        new
                        {
                            Id = 43,
                            CityId = 11,
                            Name = "Shobak"
                        },
                        new
                        {
                            Id = 44,
                            CityId = 11,
                            Name = "Al-Husseinieh"
                        },
                        new
                        {
                            Id = 45,
                            CityId = 12,
                            Name = "Ras Mounief"
                        },
                        new
                        {
                            Id = 46,
                            CityId = 12,
                            Name = "Anjara"
                        },
                        new
                        {
                            Id = 47,
                            CityId = 12,
                            Name = "Al-Wahadneh"
                        },
                        new
                        {
                            Id = 48,
                            CityId = 12,
                            Name = "Kufranjah"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Irbid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aqaba"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zarqa"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Madaba"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Albalqa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mafraq"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tafilah"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Karak"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jerash"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ma'an"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ajloun"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oncology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Radiology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Management"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("HISApp.Domain.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QTY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("HISApp.Domain.DrugOrders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QTY")
                        .HasColumnType("int");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HISApp.Domain.Emergencies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmergencyCodeId")
                        .HasColumnType("int");

                    b.Property<string>("NameOfUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyCodeId");

                    b.ToTable("Emergencies");
                });

            modelBuilder.Entity("HISApp.Domain.EmergencyCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Codes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Code BLUE",
                            Color = "#2A7DCE",
                            Description = "Represents a critical medical emergency, such as cardiopulmonary arrest, requiring immediate medical intervention.",
                            Title = "Medical Emergency"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Code RED",
                            Color = "#D94141",
                            Description = "Indicates a fire emergency, necessitating fire safety protocols and evacuation procedures",
                            Title = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Code GREY",
                            Color = "#808080",
                            Description = "indicates radioactive contamination or incidents, requiring specialized radiology and safety teams",
                            Title = "Radioactive Accident"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Code GREEN",
                            Color = "#49B06C",
                            Description = "Denotes a chemical or biological spill, requiring specialized cleanup and safety measures",
                            Title = "Chemical or Biological spillage"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Code ORANGE",
                            Color = "#F28C3A",
                            Description = "Refers to mass casualty incidents, involving coordination for large-scale emergency medical response",
                            Title = "Mass casualties"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.HospitalVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Addmission")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Discharge")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("HISApp.Domain.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalGaurdainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalGaurdainPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CityId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId1");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HISApp.Domain.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("HISApp.Domain.SickLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("SickLeaves");
                });

            modelBuilder.Entity("HISApp.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7eb60dc9-0624-464d-b714-40d7969c1bf1",
                            AccessFailedCount = 0,
                            AddressId = new Guid("15a24dfe-845b-4a6b-8381-e6af77b0aee3"),
                            Age = 40,
                            ConcurrencyStamp = "a29c25e2-16a3-4a9b-b92d-cd30cd0a8e8a",
                            DepartmentId = 1,
                            Email = "d@p2h.com",
                            EmailConfirmed = false,
                            Experience = "12",
                            FirstName = "Doctor",
                            Gender = true,
                            HireDate = new DateTime(2025, 1, 9, 3, 51, 51, 253, DateTimeKind.Local).AddTicks(8407),
                            LastName = "Ahmad",
                            LockoutEnabled = false,
                            NormalizedEmail = "D@P2H.COM",
                            NormalizedUserName = "D@P2H.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIFKxORZnf4RrJhi0nrZMrNEnsC3SRgyAItS3hv6rIKExb5pvju+ya14goKAuRFAKQ==",
                            PhoneNumber = "0781221223",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "79da8b94-93d1-450c-ab93-97c5a25bd559",
                            TwoFactorEnabled = false,
                            UserName = "d@p2h.com"
                        },
                        new
                        {
                            Id = "3357d377-776f-4414-a3eb-2d8e1fd3b025",
                            AccessFailedCount = 0,
                            AddressId = new Guid("33fa2f3e-373f-4448-b037-57745771946d"),
                            Age = 45,
                            ConcurrencyStamp = "a3cfbe71-e86b-4bad-9704-4712bd7ad98e",
                            DepartmentId = 1,
                            Email = "n@p2h.com",
                            EmailConfirmed = false,
                            Experience = "12",
                            FirstName = "Nurse",
                            Gender = false,
                            HireDate = new DateTime(2025, 1, 9, 3, 51, 51, 303, DateTimeKind.Local).AddTicks(4153),
                            LastName = "Sameera",
                            LockoutEnabled = false,
                            NormalizedEmail = "N@P2H.COM",
                            NormalizedUserName = "N@P2H.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAjcj2URZwpNfSt05xfTFX+XGpk21DPpLIyWZsj16hN6GUFRzY6CXQ7bLvZkfOwvUw==",
                            PhoneNumber = "0781227894",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "69714fde-fce7-4356-8416-a6c54996c0b2",
                            TwoFactorEnabled = false,
                            UserName = "n@p2h.com"
                        },
                        new
                        {
                            Id = "ad806a90-0577-4811-bb3e-c7589835476d",
                            AccessFailedCount = 0,
                            AddressId = new Guid("d36412b1-542d-44b9-9dd4-3bf1538149a7"),
                            Age = 40,
                            ConcurrencyStamp = "6f8c0442-0bff-4cfd-a1a8-795d4cda1c5e",
                            DepartmentId = 9,
                            Email = "m@p2h.com",
                            EmailConfirmed = false,
                            Experience = "12",
                            FirstName = "Manager",
                            Gender = true,
                            HireDate = new DateTime(2025, 1, 9, 3, 51, 51, 354, DateTimeKind.Local).AddTicks(3400),
                            LastName = "Mohammad",
                            LockoutEnabled = false,
                            NormalizedEmail = "M@P2H.COM",
                            NormalizedUserName = "M@P2H.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN9U+VDZYCi2wT0+IIEHHGCpuduvdbBcfzN3ftfdb/uyPaQbIFO8JY9zyHK/qbw/7g==",
                            PhoneNumber = "0781221244",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0a8493ab-f4d5-43e1-aa65-f4495fac8290",
                            TwoFactorEnabled = false,
                            UserName = "m@p2h.com"
                        },
                        new
                        {
                            Id = "720a2ab3-d717-48e1-81ed-f4319d99f6ba",
                            AccessFailedCount = 0,
                            AddressId = new Guid("27e8f53d-a5cd-419c-baa7-8e5545c1aaf9"),
                            Age = 33,
                            ConcurrencyStamp = "466f4cdf-0a2a-441b-925c-71c00e95691f",
                            DepartmentId = 8,
                            Email = "p@p2h.com",
                            EmailConfirmed = false,
                            Experience = "12",
                            FirstName = "Pharmacist",
                            Gender = true,
                            HireDate = new DateTime(2025, 1, 9, 3, 51, 51, 401, DateTimeKind.Local).AddTicks(7544),
                            LastName = "Ayham",
                            LockoutEnabled = false,
                            NormalizedEmail = "P@P2H.COM",
                            NormalizedUserName = "P@P2H.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPcLvJJXo4DZEQ/qb0yr+nXLTejx22bLy4P0EMaKBL9UdDij59kSq+FyRwt7sbWJKw==",
                            PhoneNumber = "0781227894",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4b2f21fa-4ded-4616-a104-c9c064e9fc31",
                            TwoFactorEnabled = false,
                            UserName = "p@p2h.com"
                        },
                        new
                        {
                            Id = "fd05d6dc-2699-4f5f-bef7-bd12ef130408",
                            AccessFailedCount = 0,
                            AddressId = new Guid("93816845-789a-4e32-967f-40cea279b8a7"),
                            Age = 26,
                            ConcurrencyStamp = "3fab5cf4-45cb-4fc9-a7db-7970b0bdc666",
                            DepartmentId = 1,
                            Email = "a@p2h.com",
                            EmailConfirmed = false,
                            Experience = "12",
                            FirstName = "Admin",
                            Gender = true,
                            HireDate = new DateTime(2025, 1, 9, 3, 51, 51, 453, DateTimeKind.Local).AddTicks(3654),
                            LastName = "Yousef",
                            LockoutEnabled = false,
                            NormalizedEmail = "A@P2H.COM",
                            NormalizedUserName = "A@P2H.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFAjDVaj/7yeITZlgPyRpmPgbcXWgQ7KzXuq2gcANA3DTwoXra7yA54H7bn8OOvScQ==",
                            PhoneNumber = "0781224567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1916a6f-6718-402c-bfda-8edeaa2cb1f2",
                            TwoFactorEnabled = false,
                            UserName = "a@p2h.com"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.VitalSigns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Breaths")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("VitalSigns");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "3",
                            Name = "ManagementStaff",
                            NormalizedName = "MANAGEMENTSTAFF"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Pharmacist",
                            NormalizedName = "PHARMACIST"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7eb60dc9-0624-464d-b714-40d7969c1bf1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "3357d377-776f-4414-a3eb-2d8e1fd3b025",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "ad806a90-0577-4811-bb3e-c7589835476d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "720a2ab3-d717-48e1-81ed-f4319d99f6ba",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "fd05d6dc-2699-4f5f-bef7-bd12ef130408",
                            RoleId = "5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HISApp.Domain.Address", b =>
                {
                    b.HasOne("HISApp.Domain.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("HISApp.Domain.Address", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HISApp.Domain.Area", b =>
                {
                    b.HasOne("HISApp.Domain.City", "City")
                        .WithMany("Areas")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("HISApp.Domain.Diagnosis", b =>
                {
                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HISApp.Domain.DrugOrders", b =>
                {
                    b.HasOne("HISApp.Domain.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("HISApp.Domain.Emergencies", b =>
                {
                    b.HasOne("HISApp.Domain.EmergencyCode", "EmergencyCode")
                        .WithMany()
                        .HasForeignKey("EmergencyCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyCode");
                });

            modelBuilder.Entity("HISApp.Domain.HospitalVisit", b =>
                {
                    b.HasOne("HISApp.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("HospitalVisits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HISApp.Domain.Patient", b =>
                {
                    b.HasOne("HISApp.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId1");

                    b.Navigation("Area");

                    b.Navigation("City");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HISApp.Domain.Prescription", b =>
                {
                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HISApp.Domain.SickLeave", b =>
                {
                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("SickLeaves")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HISApp.Domain.User", b =>
                {
                    b.HasOne("HISApp.Domain.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HISApp.Domain.VitalSigns", b =>
                {
                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("VitalSigns")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HISApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HISApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HISApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HISApp.Domain.City", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("HISApp.Domain.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HISApp.Domain.Patient", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("HospitalVisits");

                    b.Navigation("Prescriptions");

                    b.Navigation("SickLeaves");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("HISApp.Domain.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
