// <auto-generated />
using System;
using HISApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HISApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250108214311_fixing")]
    partial class fixing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HISApp.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0699e4af-6a8b-4647-80f9-f567610901ae"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "e386740c-cd9b-40e8-88b0-455bd4769f59"
                        },
                        new
                        {
                            Id = new Guid("bb2f8927-6eec-4f59-85ba-7fa71af0d4e9"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "cea7eb50-7d7e-4515-8830-f9d3f3e80753"
                        },
                        new
                        {
                            Id = new Guid("5531533d-5e32-49cf-bbce-c599db02c5a3"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "f42cf095-eed2-4f46-87f8-8abcb25eb59f"
                        },
                        new
                        {
                            Id = new Guid("a0219a68-9759-4d19-b69b-b06ab2734e37"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "5e23e00a-b0fc-4b3e-9a7f-bb9a5250e0ee"
                        },
                        new
                        {
                            Id = new Guid("0ccd5f8b-c033-42d3-9865-be981abb1344"),
                            AreaId = 1,
                            CityId = 1,
                            UserId = "974350b0-5ecb-4015-8825-19f190c268bc"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Abdoun"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Jabal Al-Weibdeh"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Sweifieh"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Name = "Dabouq"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Name = "Al-Husun"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Name = "Ar-Ramtha"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 2,
                            Name = "Al-Barheh"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 2,
                            Name = "Ar-Rabieh"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            Name = "Al-Alamieh"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 3,
                            Name = "Ar-Remal"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 3,
                            Name = "Southern Beach"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 3,
                            Name = "Wadi Rum"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 4,
                            Name = "New Zarqa"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 4,
                            Name = "Al-Ruseifa"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 4,
                            Name = "Al-Dhuleil"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 4,
                            Name = "Hashemiyah"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 5,
                            Name = "Theban"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 5,
                            Name = "Mount Nebo"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 5,
                            Name = "Al-Faisaliah"
                        },
                        new
                        {
                            Id = 20,
                            CityId = 5,
                            Name = "Ma'in"
                        },
                        new
                        {
                            Id = 21,
                            CityId = 6,
                            Name = "Salt City"
                        },
                        new
                        {
                            Id = 22,
                            CityId = 6,
                            Name = "Fuheis"
                        },
                        new
                        {
                            Id = 23,
                            CityId = 6,
                            Name = "Ain Al-Basha"
                        },
                        new
                        {
                            Id = 24,
                            CityId = 6,
                            Name = "Mahes"
                        },
                        new
                        {
                            Id = 25,
                            CityId = 7,
                            Name = "Hosha"
                        },
                        new
                        {
                            Id = 26,
                            CityId = 7,
                            Name = "Al-Khalidiya"
                        },
                        new
                        {
                            Id = 27,
                            CityId = 7,
                            Name = "Rubwa Bani Khaled"
                        },
                        new
                        {
                            Id = 28,
                            CityId = 7,
                            Name = "Um Al-Jimmal"
                        },
                        new
                        {
                            Id = 29,
                            CityId = 8,
                            Name = "Tafila City"
                        },
                        new
                        {
                            Id = 30,
                            CityId = 8,
                            Name = "Busaira"
                        },
                        new
                        {
                            Id = 31,
                            CityId = 8,
                            Name = "Al-Hasa"
                        },
                        new
                        {
                            Id = 32,
                            CityId = 8,
                            Name = "Dana"
                        },
                        new
                        {
                            Id = 33,
                            CityId = 9,
                            Name = "Karak Castle"
                        },
                        new
                        {
                            Id = 34,
                            CityId = 9,
                            Name = "Al-Qasr"
                        },
                        new
                        {
                            Id = 35,
                            CityId = 9,
                            Name = "Mu'tah"
                        },
                        new
                        {
                            Id = 36,
                            CityId = 9,
                            Name = "Al-Mazar"
                        },
                        new
                        {
                            Id = 37,
                            CityId = 10,
                            Name = "Bab Amman"
                        },
                        new
                        {
                            Id = 38,
                            CityId = 10,
                            Name = "Souf Camp"
                        },
                        new
                        {
                            Id = 39,
                            CityId = 10,
                            Name = "Sakib"
                        },
                        new
                        {
                            Id = 40,
                            CityId = 10,
                            Name = "Al-Kitta"
                        },
                        new
                        {
                            Id = 41,
                            CityId = 11,
                            Name = "Alghadeer"
                        },
                        new
                        {
                            Id = 42,
                            CityId = 11,
                            Name = "Petra"
                        },
                        new
                        {
                            Id = 43,
                            CityId = 11,
                            Name = "Shobak"
                        },
                        new
                        {
                            Id = 44,
                            CityId = 11,
                            Name = "Al-Husseinieh"
                        },
                        new
                        {
                            Id = 45,
                            CityId = 12,
                            Name = "Ras Mounief"
                        },
                        new
                        {
                            Id = 46,
                            CityId = 12,
                            Name = "Anjara"
                        },
                        new
                        {
                            Id = 47,
                            CityId = 12,
                            Name = "Al-Wahadneh"
                        },
                        new
                        {
                            Id = 48,
                            CityId = 12,
                            Name = "Kufranjah"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Irbid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aqaba"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zarqa"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Madaba"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Albalqa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mafraq"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tafilah"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Karak"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jerash"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ma'an"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ajloun"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oncology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Radiology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Management"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("HISApp.Domain.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QTY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("HISApp.Domain.DrugOrders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QTY")
                        .HasColumnType("int");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HISApp.Domain.Emergencies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmergencyCodeId")
                        .HasColumnType("int");

                    b.Property<string>("NameOfUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyCodeId");

                    b.ToTable("Emergencies");
                });

            modelBuilder.Entity("HISApp.Domain.EmergencyCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Codes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Code BLUE",
                            Color = "#2A7DCE",
                            Description = "Represents a critical medical emergency, such as cardiopulmonary arrest, requiring immediate medical intervention.",
                            Title = "Medical Emergency"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Code RED",
                            Color = "#D94141",
                            Description = "Indicates a fire emergency, necessitating fire safety protocols and evacuation procedures",
                            Title = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Code GREY",
                            Color = "#808080",
                            Description = "indicates radioactive contamination or incidents, requiring specialized radiology and safety teams",
                            Title = "Radioactive Accident"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Code GREEN",
                            Color = "#49B06C",
                            Description = "Denotes a chemical or biological spill, requiring specialized cleanup and safety measures",
                            Title = "Chemical or Biological spillage"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Code ORANGE",
                            Color = "#F28C3A",
                            Description = "Refers to mass casualty incidents, involving coordination for large-scale emergency medical response",
                            Title = "Mass casualties"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.HospitalVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Addmission")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Discharge")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("HISApp.Domain.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalGaurdainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalGaurdainPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CityId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId1");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HISApp.Domain.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("HISApp.Domain.SickLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("SickLeaves");
                });

            modelBuilder.Entity("HISApp.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e386740c-cd9b-40e8-88b0-455bd4769f59",
                            AccessFailedCount = 0,
                            AddressId = new Guid("0699e4af-6a8b-4647-80f9-f567610901ae"),
                            ConcurrencyStamp = "0924f4b2-4792-4237-93ca-8280d7bee886",
                            DepartmentId = 1,
                            Email = "d@p2h.com",
                            EmailConfirmed = false,
                            FirstName = "Doctor",
                            HireDate = new DateTime(2025, 1, 9, 0, 43, 10, 998, DateTimeKind.Local).AddTicks(2676),
                            LastName = "Ahmad",
                            LockoutEnabled = false,
                            NormalizedEmail = "d@p2h.com",
                            NormalizedUserName = "d@p2h.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEETXpoh3EVZot3ta8+ciHRpLKteQvTiXIli/F6KyTvSovxDwNSYKI/2w3LbvUFOGng==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6d79b5a6-63a5-403a-8305-a0aa7b4bb2a9",
                            TwoFactorEnabled = false,
                            UserName = "d@p2h.com"
                        },
                        new
                        {
                            Id = "cea7eb50-7d7e-4515-8830-f9d3f3e80753",
                            AccessFailedCount = 0,
                            AddressId = new Guid("bb2f8927-6eec-4f59-85ba-7fa71af0d4e9"),
                            ConcurrencyStamp = "5fec403c-276d-4e6b-b49c-fc7150ca2ec0",
                            DepartmentId = 1,
                            Email = "n@p2h.com",
                            EmailConfirmed = false,
                            FirstName = "Nurse",
                            HireDate = new DateTime(2025, 1, 9, 0, 43, 11, 45, DateTimeKind.Local).AddTicks(4501),
                            LastName = "Sameera",
                            LockoutEnabled = false,
                            NormalizedEmail = "n@p2h.com",
                            NormalizedUserName = "n@p2h.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEAMvqqoL4x/Nw+z1Wv9XRtJ/93qLKbaEQKItbxtqEOMRlfLoqfNtpV7gkdfZJ7TAlw==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c8fa9867-7308-4c89-b323-afed432f90a6",
                            TwoFactorEnabled = false,
                            UserName = "n@p2h.com"
                        },
                        new
                        {
                            Id = "f42cf095-eed2-4f46-87f8-8abcb25eb59f",
                            AccessFailedCount = 0,
                            AddressId = new Guid("5531533d-5e32-49cf-bbce-c599db02c5a3"),
                            ConcurrencyStamp = "d6c97ea8-3961-4280-ad88-f958828b92ae",
                            DepartmentId = 9,
                            Email = "m@p2h.com",
                            EmailConfirmed = false,
                            FirstName = "Manager",
                            HireDate = new DateTime(2025, 1, 9, 0, 43, 11, 93, DateTimeKind.Local).AddTicks(4816),
                            LastName = "Mohammad",
                            LockoutEnabled = false,
                            NormalizedEmail = "m@p2h.com",
                            NormalizedUserName = "m@p2h.com",
                            PasswordHash = "AQAAAAIAAYagAAAAELN+eBne+CtbA9ZHJerXiepVbrJBvfLugUr+TOlTHtJIjDNb0WzG4L6bW5ftSNVYPg==",
                            PhoneNumber = "4561237890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ff0e5142-8586-4ffb-9cf4-9e46dec0665c",
                            TwoFactorEnabled = false,
                            UserName = "m@p2h.com"
                        },
                        new
                        {
                            Id = "5e23e00a-b0fc-4b3e-9a7f-bb9a5250e0ee",
                            AccessFailedCount = 0,
                            AddressId = new Guid("a0219a68-9759-4d19-b69b-b06ab2734e37"),
                            ConcurrencyStamp = "82c7fe41-380e-47db-9205-a88694f2c303",
                            DepartmentId = 8,
                            Email = "p@p2h.com",
                            EmailConfirmed = false,
                            FirstName = "Pharmacist",
                            HireDate = new DateTime(2025, 1, 9, 0, 43, 11, 150, DateTimeKind.Local).AddTicks(1292),
                            LastName = "Ayham",
                            LockoutEnabled = false,
                            NormalizedEmail = "p@p2h.com",
                            NormalizedUserName = "p@p2h.com",
                            PasswordHash = "AQAAAAIAAYagAAAAED1YcEf6y08gDvQy13QS8vSJgYCJxFEw47JsMSIT8DmTOYBBT/VhKrp7PnPtS/KCBA==",
                            PhoneNumber = "7894561230",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62a157ae-1202-4115-a8ad-1273f3ff711c",
                            TwoFactorEnabled = false,
                            UserName = "p@p2h.com"
                        },
                        new
                        {
                            Id = "974350b0-5ecb-4015-8825-19f190c268bc",
                            AccessFailedCount = 0,
                            AddressId = new Guid("0ccd5f8b-c033-42d3-9865-be981abb1344"),
                            ConcurrencyStamp = "2fe0579c-00d0-416b-a4c0-fbf7b23ba73d",
                            DepartmentId = 1,
                            Email = "a@p2h.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            HireDate = new DateTime(2025, 1, 9, 0, 43, 11, 204, DateTimeKind.Local).AddTicks(1110),
                            LastName = "Yousef",
                            LockoutEnabled = false,
                            NormalizedEmail = "A@P2H.COM",
                            NormalizedUserName = "a@p2h.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEDUybBzosYBRm/K1ufky5BTwCiVn/UYv2Iup6hfdfDG7EilmosZX7n3GZePmOYGeCA==",
                            PhoneNumber = "3216549870",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35281e7c-37e0-439a-8ab6-9deb9585b445",
                            TwoFactorEnabled = false,
                            UserName = "a@p2h.com"
                        });
                });

            modelBuilder.Entity("HISApp.Domain.VitalSigns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Breaths")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("VitalSigns");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "3",
                            Name = "ManagementStaff",
                            NormalizedName = "MANAGEMENTSTAFF"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Pharmacist",
                            NormalizedName = "PHARMACIST"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "e386740c-cd9b-40e8-88b0-455bd4769f59",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "cea7eb50-7d7e-4515-8830-f9d3f3e80753",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "f42cf095-eed2-4f46-87f8-8abcb25eb59f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5e23e00a-b0fc-4b3e-9a7f-bb9a5250e0ee",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "974350b0-5ecb-4015-8825-19f190c268bc",
                            RoleId = "5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HISApp.Domain.Address", b =>
                {
                    b.HasOne("HISApp.Domain.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("HISApp.Domain.Address", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HISApp.Domain.Area", b =>
                {
                    b.HasOne("HISApp.Domain.City", "City")
                        .WithMany("Areas")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("HISApp.Domain.Diagnosis", b =>
                {
                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HISApp.Domain.DrugOrders", b =>
                {
                    b.HasOne("HISApp.Domain.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("HISApp.Domain.Emergencies", b =>
                {
                    b.HasOne("HISApp.Domain.EmergencyCode", "EmergencyCode")
                        .WithMany()
                        .HasForeignKey("EmergencyCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyCode");
                });

            modelBuilder.Entity("HISApp.Domain.HospitalVisit", b =>
                {
                    b.HasOne("HISApp.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("HospitalVisits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HISApp.Domain.Patient", b =>
                {
                    b.HasOne("HISApp.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId1");

                    b.Navigation("Area");

                    b.Navigation("City");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HISApp.Domain.Prescription", b =>
                {
                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HISApp.Domain.SickLeave", b =>
                {
                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("SickLeaves")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HISApp.Domain.User", b =>
                {
                    b.HasOne("HISApp.Domain.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HISApp.Domain.VitalSigns", b =>
                {
                    b.HasOne("HISApp.Domain.Patient", "Patient")
                        .WithMany("VitalSigns")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HISApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HISApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HISApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HISApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HISApp.Domain.City", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("HISApp.Domain.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HISApp.Domain.Patient", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("HospitalVisits");

                    b.Navigation("Prescriptions");

                    b.Navigation("SickLeaves");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("HISApp.Domain.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
